name: json_form_builder
description: A new Flutter package project.
version: 0.0.1
author: YuenEsc

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^4.2.0
  form_builder_image_picker: ^0.1.2
  form_builder_phone_field: ^0.1.0
  material_tag_editor: ^0.0.6
  intl: ^0.16.1
  geolocator: ^6.1.9
  geocoding: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: