name: json_form_builder
description: A new Flutter package project.
version: 0.0.1
author: YuenEsc
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder:
    git:
      url: https://github.com/YuenEsc/flutter_form_builder
      ref: master
  intl: ^0.16.1
  geolocator: ^6.1.9
  geocoding: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: