name: json_form_builder
description: A new Flutter package project.
version: 0.0.1
author: YuenEsc
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: 5.0.0-alpha.1
  form_builder_image_picker: 
    git:
      url: https://github.com/YuenEsc/form_builder_image_picker.git
  material_tag_editor: ^0.0.6
  geolocator: ^6.1.9
  geocoding: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: